# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Python Programmierkurs
author: Dennis Scheiba

exclude_patterns: [venv/*, _build, README.md]

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: "off"

# Information about where the book exists on the web
repository:
  url: https://github.com/capital-G/programmierkurs  # Online location of your book
  branch: master  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true

launch_buttons:
  notebook_interface: "jupyterlab"
  binderhub_url: "https://mybinder.org"
